---
- name: "Install build dependencies for nipapd"
  pkgng:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "py27-docutils"

- name: "Get nipapd code from git"
  git:
    repo: "git://github.com/tykling/NIPAP.git"
    dest: "{{ nipap_checkout_path }}"
    version: "freebsd-support"
  register: gitresult

- name: "make and install nipapd as needed"
  shell: 'make install'
  args:
    chdir: "{{ nipap_checkout_path }}/nipap"
    executable: "/usr/local/bin/bash"
  when: gitresult is changed

- name: "Install nipapd config file"
  template:
    src: "nipapd.conf.j2"
    dest: "/usr/local/etc/nipap/nipapd.conf"

- name: "create /var/run/nipap/"
  file:
    dest: "/var/run/nipap/"
    state: "directory"
    mode: "0700"
    owner: "nipap"
    group: "nipap"

