---
- name: "Install build dependencies for nipapd"
  pkgng:
    name: "bind911"
    state: "present"

- name: "Get nipapd code from git"
  git:
    repo: "git://github.com/tykling/NIPAP.git"
    dest: "/home/ansible/NIPAP/"
    version: "freebsd-support"
  register: gitresult

- name: "make and install nipapd as needed"
  command: 'make install'
  args:
    chdir: "/home/ansible/NIPAP/nipap"
  when: gitresult is changed

- name: "Install nipapd config file"
  template:
    src: "nipapd.conf.j2"
    dest: "/usr/local/etc/nipap/nipapd.conf"

- name: "create /var/run/nipap/"
  file:
    dest: "/var/run/nipap/"
    state: "directory"
    mode: "0700"
    owner: "nipap"
    group: "nipap"

