---
- name: "Install pip"
  pkgng:
    name: "py27-pip"
    state: "present"

- name: "Install virtualenv"
  pkgng:
    name: "py27-virtualenv"
    state: "present"

- name: "Install requirements.txt modules with pip. Install in the global py env."
  pip:
    requirements: "{{ nipap_checkout_path }}/nipap/requirements.txt"

