---
- name: "Install bind 9.11"
  pkgng:
    name: "bind911"
    state: "present"

- name: "Install bind config file"
  template:
    src: "named.conf.j2"
    dest: "/usr/local/etc/namedb/named.conf"
    mode: "0644"
    #validate: "/usr/local/sbin/named-checkconf %s"
  notify: "restart bind"

- name: "Install bind zones file"
  template:
    src: "named-zones.conf.j2"
    dest: "/usr/local/etc/namedb/named-zones.conf"
    mode: "0644"
    #validate: "/usr/local/sbin/named-checkconf %s"
  notify: "restart bind"

