---
- name: "Install alertmanager"
  pkgng:
    name: "alertmanager"
    state: "present"

- name: "Make sure alertmanager data directory exists"
  file:
    path: "/var/db/alertmanager"
    state: "directory"
    owner: "alertmanager"
    group: "alertmanager"
    mode: "0755"

