---
- name: "Install chyves"
  pkgng:
    name: "chyves" 
    state: "present"

- name: "check if zpool has been configured for use with chyves"
  shell: "/sbin/zfs list {{ chyves_zpool }}/chyves"
  register: chyves_zpool_result
  ignore_errors: True

- name: "setup chyves on zpool"
  command: "/usr/local/sbin/chyves dataset {{ chyves_zpool }} install"
  when: chyves_zpool_result.rc == 1

- name: "check if chyves bridge interfaces exist"
  command: "/sbin/ifconfig {{ item.key }}"
  register: interface_results
  with_dict: "{{ chyves_bridges }}"
  ignore_errors: True

- name: "setup chyves bridge network interfaces"
  command: "/usr/local/sbin/chyves network {{ item.key }} attach {{ item.value.interface }}"
  with_together:
    - "{{ chyves_bridges }}"
    - "{{ interface_results.results }}"
  when: item.1.rc == 1

