---
- name: "Install chyves"
  pkgng:
    name: "chyves" 
    state: "present"

- name: "check if zpool has been configured for use with chyves"
  shell: "/sbin/zfs list {{ chyves_zpool }}/chyves"
  register: chyves_zpool_result
  ignore_errors: True

- name: "setup chyves on zpool"
  command: "/usr/local/sbin/chyves dataset {{ chyves_zpool }} install"
  when: chyves_zpool_result.rc == 1

- name: "check if chyves bridge interfaces exist"
  command: "/sbin/ifconfig {{ item.key }}"
  register: interface_results
  with_dict: "{{ chyves_bridges }}"
  ignore_errors: True

- name: "setup chyves bridge network interfaces (skip bridge0)"
  command: "/usr/local/sbin/chyves network {{ item.0 }} attach {{ chyves_bridges[item.0].interface }}"
  with_together:
    - "{{ chyves_bridges }}"
    - "{{ interface_results.results }}"
  when: item.1.rc == 1

- name: "Enable chyves on boot (loads kernel modul, setup bridge0 etc)"
  service:
    name: "chyves"
    enabled: "yes"

- name: "Install qemu-utils (to convert images if needed)"
  pkgng:
    name: "qemu-utils" 
    state: "present"

- name: "Disable filtering on bridge interfaces (we filter on the individual tap interfaces instead)"
  lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: "^net.link.bridge.pfil_bridge=0$"
    state: "present"
  notify: "reload sysctl.conf"

