---
- name: "Install chyves"
  pkgng:
    name: "chyves" 
    state: "present"

- name: "check if zpool has been configured for use with chyves"
  shell: "/sbin/zfs list {{ chyves_zpool }}/chyves"
  register: chyves_zpool_result
  ignore_errors: True

- name: "setup chyves on zpool"
  command: "/usr/local/sbin/chyves dataset {{ chyves_zpool }} install"
  when: chyves_zpool_result.rc == 1

- name: "Enable chyves on boot (loads kernel module and starts rcboot vms etc)"
  service:
    name: "chyves"
    enabled: "yes"

- name: "Install qemu-utils (to convert images if needed)"
  pkgng:
    name: "qemu-utils" 
    state: "present"

- name: "Install grub2-bhyve (linux bootloader)"
  pkgng:
    name: "grub2-bhyve"
    state: "present"

- name: "Disable filtering on bridge interfaces (we filter on the individual tap interfaces instead)"
  lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: "^net.link.bridge.pfil_bridge="
    line: "net.link.bridge.pfil_bridge=0"
    state: "present"
  notify: "reload sysctl.conf"

- name: "Make chyves understand vlan interface syntax"
  lineinfile:
    dest: "/chyves/{{ chyves_zpool }}/.config/global.cfg"
    regex: "^vlan_iface_base_name="
    line: "vlan_iface_base_name={{ chyves_vlan_base_interface }}."

