---
nginx_locationslash: |
 location / {
      proxy_pass http://127.0.0.1:9093;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

supervisord_programs:
  - name: "alertmanager"
    comment: "run alertmanager"
    command: "/usr/local/bin/alertmanager --config.file=/usr/local/etc/alertmanager/alertmanager.yml --storage.path=/var/db/alertmanager"
    user: "alertmanager"

alertmanager_smtp_from: "{{ alertmanager_smtp_username }}"
alertmanager_smtp_port: 587
