---
nginx_locationslash: |
 location / {
      proxy_pass http://127.0.0.1:9093;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

alertmanager_smtp_from: "{{ alertmanager_smtp_username }}"
alertmanager_smtp_port: 587
alertmanager_smtp_tls: true
