---
- name: "Setup pf.conf"
  template:
    src: "pf.conf.j2"
    dest: "{{ pf_conf_path }}"
    validate: 'pfctl -n -f %s'
  #notify: "reload pf"

- name: "Enable pf"
  sysrc:
    name: "pf_enable"
    value: "yes"

- name: "Enable pflog"
  sysrc:
    name: "pflog_enable"
    value: "yes"

