---
- name: "Setup pf.conf for jail/vm hosts"
  template:
    src: "pf.conf.j2"
    dest: "{{ pf_conf_path }}"
    validate: 'pfctl -n -f %s'
  when: pf_jail_vm_host and not pf_gateway
  notify: "reload pf"

- name: "Setup pf.conf for gateways"
  template:
    src: "pf-gateway.conf.j2"
    dest: "{{ pf_conf_path }}"
    validate: 'pfctl -n -f %s'
  when: pf_gateway and not pf_jail_vm_host
  notify: "reload pf"

- name: "Enable CARP preempt in /etc/sysctl.conf"
  lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: "^net.inet.carp.preempt="
    line: "net.inet.carp.preempt=1"
    state: "present"
  when: pf_gateway and not pf_jail_vm_host
  notify: "reload sysctl.conf"

- name: "Enable pf"
  service:
    name: "pf"
    enabled: yes
  notify:
    - "kldload pf module"

- name: "Enable pflog"
  service:
    name: "pflog"
    enabled: yes
  notify:
    - "kldload pflog module"

