---
- name: "Install blackbox_exporter"
  pkgng:
    name: "blackbox_exporter"
    state: "present"

- name: "Install Prometheus config"
  template:
    src: "prometheus.yml.j2"
    dest: "/usr/local/etc/prometheus.yml"
    owner: "root"
    group: "wheel"
    mode: "0755"
  notify:
    - "restart prometheus"

- name: "Create supervisord.d config file to run blackbox_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "blackbox_exporter"
    supervisord_programs:
      - name: "blackbox"
        comment: "run blackbox_exporter"
        command: "/usr/local/bin/prometheus -config.file=/usr/local/etc/prometheus.yml -storage.local.path=/var/db/prometheus -log.format=logger:syslog?appname=prometheus&local=5"
        user: "prometheus"

