---
- name: "Install prometheus"
  pkgng:
    name: "prometheus"
    state: "present"

- name: "Make sure prometheus data directory exists"
  file:
    path: "/var/db/prometheus"
    state: "directory"
    owner: "prometheus"
    group: "prometheus"
    mode: "0755"

- name: "Install Prometheus config"
  template:
    src: "prometheus.yml.j2"
    dest: "/usr/local/etc/prometheus.yml"
    owner: "root"
    group: "wheel"
    mode: "0755"
  notify:
    - "restart prometheus"

