---
- name: "add syslog.d config for prometheus"
  copy:
    src: "prometheus-syslogd.conf"
    dest: "/usr/local/etc/syslog.d/prometheus.conf"
  notify:
    - "restart prometheus"

- name: "Make sure /var/log/prometheus.log exists"
  copy:
    dest: "/var/log/prometheus.log"
    content: ""
    force: no
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"

