---
- name: "Install node_exporter"
  pkgng:
    name: "node_exporter"
    state: "present"

- name: "Enable node_exporter"
  service:
    name: "node_exporter"
    enabled: yes

- name: "Start node_exporter"
  service:
    name: "node_exporter"
    state: "started"

