---
- name: "Install node_exporter"
  pkgng:
    name: "node_exporter"
    state: "present"

- name: "Enable node_exporter"
  service:
    name: "node_exporter"
    enabled: yes

- name: "Start node_exporter"
  service:
    name: "node_exporter"
    state: "started"

- name: "Set node_exporter_args in /etc/rc.conf - hardcode for jailhosts only for now"
  sysrc:
    name: "node_exporter_args"
    value: "--web.telemetry-path='/prometheusproxy/jailhost/metrics'"

