---
- name: configure ezjail hosts
  hosts: ezjail_hosts
  become: yes
  roles:
    - freebsd_base
    - ezjail_host
  tags:
    - ezjail_hosts

- name: configure censurfridns anycast jail hosts
  hosts: anycast_jail_hosts
  become: yes
  roles:
    - freebsd_base
    - anycast_jail_host
  tags:
    - anycast_jail_hosts

- name: configure freebsd hosts (physical servers)
  hosts: freebsd_hosts
  become: yes
  roles:
    freebsd_host

##############################################################################
### application roles below here

- name: configure etherpad servers
  hosts: etherpad_servers
  become: yes
  roles:
    - freebsd_base
    - etherpad_server
  tags:
    - etherpad_servers

- name: configure all murmur servers
  hosts: murmur_servers
  become: yes
  roles:
    - freebsd_base
    - murmur_server
  tags:
    - murmur_servers

- name: configure all nginx http and https servers
  hosts: nginx_servers
  become: yes
  roles:
    - freebsd_base
    - nginx_server
  tags:
    - nginx_servers

- name: configure dovecot servers
  hosts: dovecot_servers
  become: yes
  roles:
    - freebsd_base
    - dovecot_server
  tags:
    - dovecot_servers

- name: configure erlang webservers
  hosts: erlang_web_servers
  become: yes
  roles:
    - freebsd_base
    - erlang_web_server
  tags:
    - erlang_web_servers

- name: configure wiki servers
  hosts: mediawiki_servers
  become: yes
  roles:
    - freebsd_base
    - mediawiki_server
  tags:
    - mediawiki_servers

- name: configure people servers
  hosts: people_servers
  become: yes
  roles:
    - freebsd_base
    - people_server
  tags:
    - people_servers

- name: configure postfix servers
  hosts: postfix_servers
  become: yes
  roles:
    - freebsd_base
    - postfix_server
  tags:
    - postfix_servers

- name: configure tor servers
  hosts: tor_servers
  become: yes
  roles:
    - freebsd_base
    - tor_server
  tags:
    - tor_servers

- name: configure django servers
  hosts: django_servers
  become: yes
  roles:
    - freebsd_base
    - django_server
  tags:
    - django_servers

- name: configure bornhack django servers
  hosts: bh_django_servers
  become: yes
  roles:
    - freebsd_base
    - bh_django_server
  tags:
    - bh_django_servers


