---
- name: "configure basic freebsd stuff"
  hosts: "freebsd"
  become: yes
  roles:
    - "freebsd_base"
  tags:
    - "freebsd_base"

- name: "configure freebsd hosts (physical servers)"
  hosts: "freebsd_hosts"
  become: yes
  roles:
    - "freebsd_host"
  tags:
    - "freebsd_hosts"

- name: "configure ezjail hosts"
  hosts: "ezjail_hosts"
  become: yes
  roles:
    - "ezjail_host"
  tags:
    - "ezjail_hosts"

- name: "configure censurfridns anycast jail hosts"
  hosts: "anycast_jail_hosts"
  become: yes
  roles:
    - "anycast_jail_host"
  tags:
    - "anycast_jail_hosts"

- name: "configure chyves bhyve hosts"
  hosts: "chyves_hosts"
  become: yes
  roles:
    - "chyves_host"
  tags:
    - "chyves_hosts"

##############################################################################
### application roles below here

- name: "configure etherpad servers"
  hosts: "etherpad_servers"
  become: yes
  roles:
    - "etherpad_server"
  tags:
    - "etherpad_servers"

- name: "configure all murmur servers"
  hosts: "murmur_servers"
  become: yes
  roles:
    - "murmur_server"
  tags:
    - "murmur_servers"

- name: "configure all nginx http and https servers"
  hosts: "nginx_servers"
  become: yes
  roles:
    - "nginx_server"
  tags:
    - "nginx_servers"

- name: "configure dovecot servers"
  hosts: "dovecot_servers"
  become: yes
  roles:
    - "dovecot_server"
  tags:
    - "dovecot_servers"

- name: "configure erlang webservers"
  hosts: "erlang_web_servers"
  become: yes
  roles:
    - "erlang_web_server"
  tags:
    - "erlang_web_servers"

- name: "configure wiki servers"
  hosts: "mediawiki_servers"
  become: yes
  roles:
    - "mediawiki_server"
  tags:
    - "mediawiki_servers"

- name: "configure people servers"
  hosts: "people_servers"
  become: yes
  roles:
    - "people_server"
  tags:
    - "people_servers"

- name: "configure postfix servers"
  hosts: "postfix_servers"
  become: yes
  roles:
    - "postfix_server"
  tags:
    - "postfix_servers"

- name: "configure tor servers"
  hosts: "tor_servers"
  become: yes
  roles:
    - "tor_server"
  tags:
    - "tor_servers"

- name: "configure django servers"
  hosts: "django_servers"
  become: yes
  roles:
    - "django_server"
  tags:
    - "django_servers"

- name: "configure bornhack django servers"
  hosts: "bh_django_servers"
  become: yes
  roles:
    - "bh_django_server"
  tags:
    - "bh_django_servers"

- name: "configure kea dhcp servers"
  hosts: "kea_servers"
  become: yes
  roles:
    - "kea_server"
  tags:
    - "kea_servers"

- name: "configure znc servers"
  hosts: "znc_servers"
  become: yes
  roles:
    - "znc_server"
  tags:
    - "znc_servers"

- name: "configure isc dhcp servers"
  hosts: "isc_dhcpd_servers"
  become: yes
  roles:
    - "isc_dhcpd_server"
  tags:
    - "isc_dhcpd_servers"

- name: "configure metabase servers"
  hosts: "metabase_servers"
  become: yes
  roles:
    - "metabase_server"
  tags:
    - "metabase_servers"

- name: "configure certgrinder servers"
  hosts: "certgrinder_servers"
  become: yes
  roles:
    - "certgrinder_server"

- name: "configure certgrinder clients"
  hosts: "certgrinder_clients"
  become: yes
  roles:
    - "certgrinder_client"

- name: "configure charybdis ircd servers"
  hosts: "ircd_servers"
  become: yes
  roles:
    - "ircd_server"

- name: "configure PostgreSQL servers"
  hosts: "postgresql_servers"
  become: yes
  roles:
    - "postgresql_server"

- name: "configure Unbound servers"
  hosts: "unbound_servers"
  become: yes
  roles:
    - "unbound_server"

- name: "configure syslog-ng servers"
  hosts: "syslogng_servers"
  become: yes
  roles:
    - "syslogng_server"

- name: "configure zabbix servers"
  hosts: "zabbix_servers"
  become: yes
  roles:
    - "zabbix_server"

- name: "configure zabbix frontend servers"
  hosts: "zabbix_frontend_servers"
  become: yes
  roles:
    - "zabbix_frontend_server"

- name: "configure tykdnscheck servers"
  hosts: "tykdnscheck_servers"
  become: yes
  roles:
    - "tykdnscheck_server"

- name: "configure roundcube servers"
  hosts: "roundcube_servers"
  become: yes
  roles:
    - "roundcube_server"

- name: "configure nfsen servers"
  hosts: "nfsen_servers"
  become: yes
  roles:
    - "nfsen_server"

- name: "configure tykbackup servers"
  hosts: "tykbackup_servers"
  become: yes
  roles:
    - "tykbackup_server"

- name: "configure download servers"
  hosts: "download_servers"
  become: yes
  roles:
    - "download_server"

