---
- name: configure etherpad servers
  hosts: etherpad_servers
  become: yes
  roles:
    - etherpad_server
  tags:
    - etherpad_servers

- name: configure all jail hosts
  hosts: jail_hosts
  become: yes
  roles:
    - jail_host
  tags:
    - jail_hosts

- name: configure all censurfridns anycast jail hosts
  hosts: anycast_jail_hosts
  become: yes
  roles:
    - anycast_jail_host
  tags:
    - anycast_jail_hosts

- name: configure all murmur servers
  hosts: murmur_servers
  become: yes
  roles:
    - murmur_server
  tags:
    - murmur_servers

- name: configure all http servers
  hosts: nginx_http_servers
  become: yes
  roles:
    - nginx_http_server
  tags:
    - nginx_http_servers

- name: configure all https servers
  hosts: nginx_https_servers
  become: yes
  roles:
    - nginx_https_server
  tags:
    - nginx_https_servers

- name: configure dovecot servers
  hosts: dovecot_servers
  roles:
    - dovecot_server
  tags:
    - dovecot_servers

- name: configure erlang webservers
  hosts: erlang_web_servers
  roles:
    - erlang_web_server
  tags:
    - erlang_web_servers

- name: configure wiki servers
  hosts: mediawiki_servers
  roles:
    - mediawiki_server
  tags:
    - mediawiki_servers

- name: configure nginx ssh servers
  hosts: nginx_ssh_servers
  roles:
    - nginx_ssh_server
  handlers:
    - include: handlers/handlers.yml
  tags:
    - nginx_ssh_servers

- name: configure postfix servers
  hosts: postfix_servers
  roles:
    - postfix_server
  tags:
    - postfix_servers

- name: configure tor servers
  hosts: tor_servers
  roles:
    - tor_server
  tags:
    - tor_servers

