---
- name: "Copy nginx.conf"
  template:
    src: "nginx.conf.j2"
    dest: "/usr/local/etc/nginx/nginx.conf"
  notify: "reload nginx"

- name: "Copy default nginx TLS config"
  template:
    src: "tls.conf.j2"
    dest: "/usr/local/etc/nginx/tls.conf"
  when: nginx_proxy
  notify: "reload nginx"

- name: "Copy nginx securityheaders.conf"
  template:
    src: "securityheaders.conf.j2"
    dest: "/usr/local/etc/nginx/securityheaders.conf"
  when: nginx_proxy
  notify: "reload nginx"

- name: "Copy nginx proxyheaders.conf"
  template:
    src: "proxyheaders.conf.j2"
    dest: "/usr/local/etc/nginx/proxyheaders.conf"
  when: nginx_proxy
  notify: "reload nginx"

- name: "Include node specific nginx_extra_configs.yml where needed (legacy, remove when possible)"
  include_vars: "../host_vars/{{ ansible_nodename }}-nginx_extra_configs.yml"
  ignore_errors: yes

- name: "Include common nginx_extra_configs.yml where needed"
  include_vars:
    file: "../include_vars/nginx_extra_configs.yml"
    name: "nginx_common_extra_configs"
  ignore_errors: yes

- name: "Create nginx extra include configs (acls and more)"
  copy:
    owner: "root"
    group: "wheel"
    mode: "600"
    content: "{{ item.value.content }}"
    dest: "/usr/local/etc/nginx/{{ item.value.filename }}"
  with_dict: "{{ nginx_extra_configs | combine(nginx_common_extra_configs) | default({}) }}"
  notify: "reload nginx"

- name: "Copy vhost http configs for http enabled vhosts"
  template:
    src: "http-vhost.conf.j2"
    dest: "/usr/local/etc/nginx/vhosts/{{ item.value.hostnames[0] }}-http.conf"
  with_dict: "{{ vhosts | default({}) }}"
  when:
    - nginx_proxy
    - (('http' in item.value and item.value.http) or 'http' not in item.value)
  notify: "reload nginx"

- name: "Copy vhost https configs for https enabled vhosts"
  template:
    src: "https-vhost.conf.j2"
    dest: "/usr/local/etc/nginx/vhosts/{{ item.value.hostnames[0] }}-https.conf"
  with_dict: "{{ vhosts | default({}) }}"
  when:
    - nginx_proxy
    - (('https' in item.value and item.value.https) or 'https' not in item.value)
  notify: "reload nginx"

