---
- include_tasks: "nginx.yml"
- include_tasks: "syslog.yml"
- include_tasks: "directories.yml"
- include_tasks: "dhparam.yml"
- include_tasks: "configs.yml"
- include_tasks: "ocsp.yml"
  when:
    - nginx_proxy
    - certgrinder_hostname_sets is defined

