---
- name: "Include secrets file if present"
  include_vars: "/usr/local/etc/ansible/host_vars/{{ ansible_nodename }}-secrets.yml"
  ignore_errors: yes

- name: "Install nginx"
  pkgng:
    name: "nginx"
    state: "present"

- name: "Enable nginx"
  service:
    name: "nginx"
    enabled: "yes"

- name: "Run certgrinder"
  command: "/usr/bin/su {{ certgrinder_user }} -c '/usr/home/{{ certgrinder_user }}/virtualenv/bin/python /usr/home/{{ certgrinder_user }}/certgrinder/certgrinder.py /usr/home/{{ certgrinder_user }}/certgrinder/certgrinder.yml'"
  when: nginx_proxy

- name: "Create dhparams"
  shell: "/usr/local/bin/openssl dhparam 4096 > {{ nginx_dhparam_path }}"
  args:
    creates: "{{ nginx_dhparam_path }}"
  when: nginx_proxy
 
- name: "Make sure nginx is started"
  service:
    name: "nginx"
    state: "started"

