---
- name: "Install nginx"
  pkgng:
    name: "nginx"
    state: "present"

- name: "Enable nginx"
  service:
    name: "nginx"
    enabled: yes

- name: "Create dhparams"
  shell: "/usr/local/bin/openssl dhparam 4096 > {{ nginx_dhparam_path }}"
  args:
    creates: "{{ nginx_dhparam_path }}"
  when:
    - nginx_proxy
    - certgrinder_hostname_sets is defined

