---
- name: "Include host_vars/{{ ansible_nodename }}-secrets.yml if it exists"
  include_vars: "/usr/local/etc/ansible/host_vars/{{ ansible_nodename }}-secrets.yml"
  ignore_errors: yes
  tags:
    - always

- name: Copy vhost http configs
  template:
    src: http-vhost.conf.j2
    dest: "/usr/local/etc/nginx/vhosts/{{ item.value.hostnames[0] }}-http.conf"
  with_dict: "{{ vhosts }}"

- name: Reload nginx configs
  service:
    name: nginx
    state: reloaded

- name: Check if we have certificates for all vhosts
  stat:
    path: "/usr/home/{{ certgrinder_user }}/certificates/{{ item.value.hostnames[0] }}.crt"
  register: certresult
  with_dict: "{{ vhosts }}"

- name: Copy vhost https configs (only when a cert exists)
  template:
    src: https-vhost.conf.j2
    dest: "/usr/local/etc/nginx/vhosts/{{ item.value.hostnames[0] }}-https.conf"
  with_together:
    - "{{ vhosts }}"
    - "{{ certresult.results }}"
  when: item.1.stat.exists

- name: Copy custom vhosts
  copy:
    owner: root
    group: wheel
    mode: "600"
    content: "{{ item.value.content }}"
    dest: "/usr/local/etc/nginx/vhosts/{{ item.value.filename }}.conf"
  with_dict: "{{ custom_vhosts | default({}) }}"
 
