---
- name: "Install pip"
  pkgng:
    name: "py27-pip"
    state: "present"

- name: "Install virtualenv"
  pkgng:
    name: "py27-virtualenv"
    state: "present"

- name: "Install python 3.5 for django virtualenv"
  pkgng:
    name: "python35"
    state: "present"

- name: "Install OS dependencies for django"
  pkgng:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ django_os_dependencies + django_extra_os_dependencies | default([]) }}"

- name: "Install gettext-tools if neded"
  pkgng:
    name: "gettext-tools"
    state: "present"
  when: django_i18n | default(False)

- name: "Install needed pip modules"
  pip:
    requirements: "{{ django_pip_requirements_path }}"
    virtualenv: "{{ django_virtualenv_path }}"
    virtualenv_python: "{{ django_python_path }}"

