---
- name: "Create supervisord.d config file to run django"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "django"
    supervisord_programs:
      - name: "redis"
        comment: "run redis"
        command: "/usr/local/bin/redis-server /usr/local/etc/redis.conf"
        user: "535" # 535 is the redis uid on freebsd
        priority: "1"

      - name: "daphne"
        comment: "run daphne"
        command: "{{ django_virtualenv_path }}/bin/python -u {{ django_virtualenv_path }}/bin/daphne --access-log - --proxy-headers {{ django_mainapp }}.asgi:channel_layer"
        user: "{{ django_daphne_user }}"
        directory: "{{ django_root }}"
        priority: "2"

      - name: "runworker"
        comment: "run asgi workers"
        command: "{{ django_virtualenv_path }}/bin/python -u {{ django_root }}/manage.py runworker"
        numprocs: "{{ django_asgi_worker_count }}"
        user: "www"
        priority: "3"

