---
- name: "Add certgrinder user"
  user:
    name: "{{ certgrinder_user }}"
    comment: "certgrinder user"

- name: "Add ssh authorized_keys for certgrinder user"
  authorized_key:
    user: "{{ certgrinder_user }}"
    key: "{{ item }}"
  with_items: "{{ certgrinder_authorized_keys }}"

- name: "Add certgrinder user to sudoers"
  lineinfile:
    dest: "/usr/local/etc/sudoers"
    state: "present"
    regexp: "^{{ certgrinder_user }} ALL=\\(ALL\\) NOPASSWD: /usr/local/bin/certbot$"
    line: "{{ certgrinder_user }} ALL=(ALL) NOPASSWD: /usr/local/bin/certbot"
    validate: "visudo -cf %s"

