---
- name: "Add certgrinder user"
  user:
    name: "{{ certgrinder_user }}"
    comment: "certgrinder user"

- name: "Add ssh authorized_keys for certgrinder user"
  authorized_key:
    user: "{{ certgrinder_user }}"
    key: "{{ item.value.authkey }}"
    key_options: "from={{ item.value.fromip }},command=/usr/local/bin/certgrinder,no-port-forwarding,no-x11-forwarding,no-agent-forwarding"
  with_dict: "{{ certgrinder_authorized_keys }}"

- name: "Add certgrinder user to sudoers"
  lineinfile:
    dest: "/usr/local/etc/sudoers"
    state: "present"
    regexp: "^{{ certgrinder_user }} ALL=\\(ALL\\) NOPASSWD: /usr/local/bin/certbot$"
    line: "{{ certgrinder_user }} ALL=(ALL) NOPASSWD: /usr/local/bin/certbot"
    validate: "visudo -cf %s"

