---
- name: "Create supervisord logfile directory"
  file:
    path: "/var/log/supervisord"
    state: "directory"
    owner: "root"
    group: "wheel"

- name: "Add django.log to syslog.conf"
  blockinfile:
    dest: "/etc/syslog.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for supervisord django log"
    block: |
      !supervisord
      *.*                                             /var/log/supervisord/django.log

- name: "Create django.log if it doesn't exist"
  file:
    path: "/var/log/supervisord/django.log"
    state: "touch"
    mode: "644"

- name: "Reload syslogd"
  service:
    name: "syslogd"
    state: "reloaded"

