---
- name: "Add circusd.log to syslog.conf"
  lineinfile:
    dest: "/etc/syslog.conf"
    line: "local2.*                                        /var/log/circusd.log"
  notify: "reload syslogd"

- name: "Make sure the circusd logfile exists"
  copy:
    dest: "/var/log/circusd.log"
    content: ""
    force: no
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "reload syslogd"

