---
- name: Install uwsgi
  pkgng:
    name: uwsgi
    state: present

- name: Remove buggy line from uwsgi rc.d script
  lineinfile:
    dest: "/usr/local/etc/rc.d/uwsgi"
    line: ': ${uwsgi_procname="${command}"}'
    state: absent

- name: Enable uwsgi
  service:
    name: uwsgi
    enabled: yes

- name: Define uwsgi flags in rc.conf
  sysrc:
    name: uwsgi_flags
    value: "--ini /usr/local/etc/uwsgi/uwsgi.ini"

- name: Define uwsgi uid in rc.conf
  sysrc:
    name: uwsgi_uid
    value: "80"

- name: Define uwsgi gid in rc.conf
  sysrc:
    name: uwsgi_gid
    value: "80"

- name: Define uwsgi program in rc.conf
  sysrc:
    name: uwsgi_program
    value: "{{ django_virtualenv_path }}/bin/uwsgi"

- name: Create uwsgi config directory
  file:
    path: /usr/local/etc/uwsgi
    state: directory

- name: Copy uwsgi config file
  template:
    src: uwsgi.ini.j2
    dest: /usr/local/etc/uwsgi/uwsgi.ini

- name: Start uwsgi (if neccesary)
  service:
    name: uwsgi
    state: started

- name: Reload uwsgi
  service:
    name: uwsgi
    state: reloaded
  tags:
    - codedeploy

