---
- name: "Add authorized_keys for ansible user"
  copy:
    owner:  "ansible"
    group:  "ansible"
    mode: "0644"
    content: "{{ ansible_authorized_keys_file }}"
    dest: "/usr/home/ansible/.ssh/authorized_keys"
  tags:
    - "ansiblekeys"

