---
- name: "Add custom crontab jobs for this host"
  blockinfile:
    dest: "/etc/crontab"
    marker: "# {mark} ANSIBLE MANAGED BLOCK crontab jobs"
    content: |
      {% for job in crontab_jobs | default([]) %}
      {% if job.minute is defined %}{{ job.minute }}{% else %}*{% endif %} {% if job.hour is defined %}{{ job.hour }}{% else %}*{% endif %} {% if job.mday is defined %}{{ job.mday }}{% else %}*{% endif %} {% if job.month is defined %}{{ job.month }}{% else %}*{% endif %} {% if job.wday is defined %}{{ job.wday }}{% else %}*{% endif %} {{ job.user }} {{ job.command }}
      {% endfor %}

