---
- name: "Configure /etc/hosts"
  blockinfile:
    create: yes
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK /etc/hosts"
    content: "{{ etchosts }}"
  when: etchosts is defined

