---
- include_tasks: "etchosts.yml"
- include_tasks: "pkg.yml"
- include_tasks: "packages.yml"
- include_tasks: "users.yml"
- include_tasks: "motd.yml"
- include_tasks: "resolvconf.yml"
- include_tasks: "sshd.yml"
- include_tasks: "syslog.yml"
- include_tasks: "resolvconf.yml"
- include_tasks: "etcaliases.yml"
- include_tasks: "postfixnullmailer.yml"
  when: "'postfix_servers' not in group_names"

