---
- name: "Add /etc/rc.conf.d/netif/* files for proxyarp hosts"
  template:
    src: "proxyarp-netif"
    dest: "/etc/rc.conf.d/netif/{{ item.name }}"
  with_items: "{{ proxyarp_configs | default([]) }}"
  tags:
    - "proxyarp"

- name: "Add /etc/rc.conf.d/routing/* files for proxyarp hosts"
  template:
    src: "proxyarp-routing"
    dest: "/etc/rc.conf.d/routing/{{ item.name }}"
  with_items: "{{ proxyarp_configs | default([]) }}"
  tags:
    - "proxyarp"

- name: "Add devd script to down/up customer interfaces on CARP events"
  template:
    src: "proxyarp-carp-control.sh.j2"
    dest: "/usr/local/bin/proxyarp-carp-control.sh"
    mode: "0755"

- name: "Add devd config to call proxyarp-carp-control.sh"
  template:
    src: "proxyarp-carp.j2"
    dest: "/etc/devd/proxyarp-carp"

