---
- name: "Add /etc/rc.conf.d/netif/* files for proxyarp hosts"
  template:
    src: "proxyarp-netif"
    dest: "/etc/rc.conf.d/netif/{{ item.name }}"
  with_items: "{{ proxyarp_configs | default([]) }}"

- name: "Add /etc/rc.conf.d/routing/* files for proxyarp hosts"
  template:
    src: "proxyarp-routing"
    dest: "/etc/rc.conf.d/routing/{{ item.name }}"
  with_items: "{{ proxyarp_configs | default([]) }}"

