---
- name: Set remote loghost in /etc/syslog.conf
  lineinfile:
    dest: /etc/syslog.conf
    line: "*.*                                        @{{ syslog_server_ip }}"
  when: syslog_server_ip | default(False)
  notify: "Reload syslogd"

