---
- name: "Install getmail"
  pkgng:
    name: "getmail"
    state: "present"

- name: "add getmail user"
  user:
    name: "{{ getmail_user }}"
    comment: "getmail user"

- name: "Create getmail config directory"
  file:
    path: "/home/getmail/.getmail"
    state: "directory"
    owner: "getmail"
    group: "getmail"
    mode: "0700"

- name: "add getmail config files"
  template:
    src: "getmailrc.j2"
    dest: "/usr/home/{{ getmail_user }}/.getmail/{{ item[1].name }}{{ item[0] }}rc"
    mode: "0600"
    owner: "{{ getmail_user }}"
    group: "{{ getmail_user }}"
  with_nested:
    - "{{ getmail_actions | default([]) }}"
    - "{{ getmail_mailboxes | default([]) }}"

