---
- name: "Install getmail"
  pkgng:
    name: "getmail"
    state: "present"

- name: "add getmail user"
  user:
    name: "{{ getmail_user }}"
    comment: "getmail user"

- name: "Create getmail config directory"
  file:
    path: "/home/getmail/.getmail"
    state: "directory"
    owner: "getmail"
    group: "getmail"
    mode: "0700"

- name: "add getmail config files"
  template:
    src: "getmailrc.j2"
    dest: "{{ getmail_path }}/{{ item[1].filename }}{{ item[0] }}rc"
    mode: "0600"
    owner: "{{ getmail_user }}"
    group: "{{ getmail_user }}"
  with_nested:
    - "{{ getmail_actions | default([]) }}"
    - "{{ getmail_mailboxes | default([]) }}"

- name: "Enable cronjobs to run getmail"
  cron:
    name: "Run getmail for {{ item[1].filename }} {{ item[0] }}"
    job: "/usr/local/bin/getmail --rcfile {{ getmail_path }}/{{ item[1].filename }}{{ item[0] }}rc"
    cron_file: "/etc/crontab"
    user: "getmail"
  with_nested:
    - "{{ getmail_actions | default([]) }}"
    - "{{ getmail_mailboxes | default([]) }}"

