---
- name: "Install msmtp"
  pkgng:
    name: "msmtp"
    state: "present"

- name: "Copy msmtp config file"
  template:
    src: "msmtp.conf.j2"
    dest: "/usr/local/etc/msmtprc"
    mode: "0600"
    owner: "www"
    group: "www"

- name: "Copy msmtp wrapper file"
  copy:
    src: "msmtp_wrapper.sh"
    dest: "/usr/local/bin/msmtp_wrapper.sh"
    mode: "0755"
    owner: "root"
    group: "wheel"

