---
- name: "Install rt44"
  pkgng:
    name: "rt44"
    state: "present"

- name: "disable html escaping of signatures patch"
  patch:
    src: "disable_html_escaping_signatures.patch"
    dest: "/usr/local/share/rt44/html/Elements/MessageBox"
  when: rt_allow_html_signatures | default(no)
  notify:
    - "clear rt mason cache"
    - "restart spawn-fcgi"

- name: "apply remove signature footer patch"
  patch:
    src: "rt_remove_signature_footer.patch"
    dest: "/usr/local/share/rt44/html/Elements/MessageBox"
  when: rt_patch_signature_footer | default(no)
  notify:
    - "clear rt mason cache"
    - "restart spawn-fcgi"

