---
- name: "Make sure the process accounting file exists"
  copy:
    dest: "{{ process_accounting_file }}"
    content: ""
    force: no
    owner: "root"
    group: "wheel"
    mode: "0600"

- name: "Enable process accounting"
  service:
    name: "accounting"
    enabled: yes
  notify:
    - "start process accounting"

