---
- include_tasks: "packages.yml"
- include_tasks: "openntpd.yml"
- include_tasks: "smartd.yml"
  when: smartd
- include_tasks: "zfs-periodic.yml"
- include_tasks: "zfs-scrub.yml"
- include_tasks: "netdata.yml"
- include_tasks: "aesni.yml"
- include_tasks: "sysctl.yml"

