---
- name: "install tykroutefix rc.d script"
  copy:
    src: "tykroutefix"
    dest: "/etc/rc.d/tykroutefix"
    mode: "0755"
  when: tykroutefix | default(False)

- name: "enable tykroutefix in rc.conf"
  sysrc:
    name: "tykroutefix_enable"
    value: "YES"
  when: tykroutefix | default(False)

