---
- name: "Enable VMware guestd"
  sysrc:
    name: "vmware_guestd_enable"
    value: "YES"

- name: "Make sure VMware guestd is running"
  service:
    name: "vmware-guestd"
    enabled: yes

- name: "Enable VMware kernel module(s)"
  sysrc:
    name: "vmware_guest_{{ item }}_enable"
    value: "YES"
  with_items: "{{ vmware_kernel_modules }}"
