---
- name: "Configure periodic zfs scrubs"
  blockinfile:
    path: "/etc/periodic.conf"
    block: |
      #monthly zfs scrub
      daily_scrub_zfs_enable="YES"
      daily_scrub_zfs_default_threshold={{ zfs_scrub_interval_days }}

