---
- name: "Configure periodic zfs scrubs"
  blockinfile:
    dest: "/etc/periodic.conf"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK zfs-scrub"
    block: |
      #monthly zfs scrub
      daily_scrub_zfs_enable="YES"
      daily_scrub_zfs_default_threshold={{ zfs_scrub_interval_days }}

