---
- name: "Include secrets file if present"
  include_vars: "/usr/local/etc/ansible/host_vars/{{ ansible_nodename }}-secrets.yml"
  ignore_errors: yes

- name: "Install isc dhcpd"
  pkgng:
    name: "isc-dhcp43-server"
    state: "present"

- name: "Enable isc dhcpd in rc.conf"
  sysrc:
    name: "dhcpd_enable"
    value: "YES"

- name: "Copy dhcpd.conf"
  template:
    src: "dhcpd.conf.j2"
    dest: "/usr/local/etc/dhcpd.conf"
  notify: "restart isc dhcpd"

