---
- name: Add dhcpd.log to syslog.conf
  lineinfile:
    dest: /etc/syslog.conf
    regexp: "^local6"
    line: "local6.*                                        /var/log/dhcpd.log"
  notify: "restart syslogd"

- name: Create dhcpd.log if it doesn't exist
  file:
    path: /var/log/dhcpd.log
    state: touch
    mode: "640"
  notify: "restart syslogd"

- name: Add dhcpd.log to newsyslog.conf
  lineinfile:
    dest: /etc/newsyslog.conf
    regexp: "^/var/log/dhcpd.log "
    line: "/var/log/dhcpd.log                    640  365   *    @T00  JC"

