---
- name: "Create supervisord.d config file to run uwsgi"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "uwsgi"
    supervisord_programs:
      - name: "uwsgi"
        comment: "run uwsgi"
        command: "/usr/local/bin/uwsgi --ini /usr/local/etc/uwsgi/uwsgi.ini --logger syslog --stats /var/run/uwsgi/stats.sock --lazy-apps --touch-chain-reload /var/run/uwsgi/touch-to-reload-uwsgi --pidfile /var/run/uwsgi/uwsgi.pid -s /var/run/uwsgi/uwsgi.sock --uid 80 --gid 80"
        user: "www"
        stopsignal: "INT"

