---
- name: Install nginx
  pkgng:
    name: nginx
    state: present

- name: Enable nginx
  service:
    name: nginx
    enabled: yes

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf

- name: Create nginx logfile directory
  file:
    path: /usr/local/www/logs
    state: directory

- name: Start Nginx (if not running)
  service:
    name: nginx
    state: started

- name: Reload nginx config
  service:
    name: nginx
    state: reloaded

