---
- name: "Install OoklaServer binary"
  file:
    src: "OoklaServer"
    dest: "/usr/local/bin/OoklaServer"
    mode: "755"

- name: "Install OoklaServer config"
  template:
    src: "OoklaServer.properties.j2"
    dest: "/usr/local/etc/OoklaServer.properties"

- name: "Download http_legacy_fallback.zip"
  get_url:
    url: "http://install.speedtest.net/httplegacy/http_legacy_fallback.zip"
    dest: "/home/ansible/http_legacy_fallback.zip"
    checksum: "sha256:e77a8fc73dbf725c6d529b389e2fa0af61fbad9be2240d79dc6db078f245463d"
  register: downloadresult

- name: "Create /usr/local/www/speedtest-legacy"
  file:
    dest: "/usr/local/www/speedtest-legacy"
    state: "directory"

- name: "Extract http_legacy_fallback.zip into /usr/local/www/speedtest-legacy"
  unarchive:
    src: "/home/ansible/http_legacy_fallback.zip"
    dest: "/usr/local/www/speedtest-legacy"
    remote_src: True
  when: downloadresult is changed

