---
- name: "Create supervisord.d config file to run OoklaServer"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "ooklaserver"
    supervisord_programs:
      - name: "ooklaserver"
        comment: "run ooklaserver"
        command: "/usr/local/ookla/OoklaServer"
        user: "speedtest"

