---
- name: "Install poudriere"
  pkgng:
    name: "poudriere"
    state: present

- name: "Copy poudriere.conf"
  template:
    src: "poudriere.conf.j2"
    dest: "/usr/local/etc/poudriere.conf"

- name: "Copy poudriere.sh"
  template:
    src: "poudriere.sh.j2"
    dest: "/usr/local/bin/poudriere.sh"
    mode: "0755"

