---
- name: "Create supervisord.d config file to run tykdnscheck4"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "tykdnscheck4"
    supervisord_programs:
      - name: "tykdnscheck4"
        comment: "run tykdnscheck4"
        command: "/usr/home/tykdnscheck/tykdnscheck/tykdnscheck.sh -p 4 -d check.censurfridns.dk. -l /var/log/dnscheck4.log -i {{ tykdnscheck_okservers_v4 | join(' ') }} -g '{{ tykdnscheck_goodmessage }}' -b '{{ tykdnscheck_badmessage }}'"
        user: "0"

- name: "Create supervisord.d config file to run tykdnscheck6"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "tykdnscheck6"
    supervisord_programs:
      - name: "tykdnscheck6"
        comment: "run tykdnscheck6"
        command: "/usr/home/tykdnscheck/tykdnscheck/tykdnscheck.sh -p 6 -d check.censurfridns.dk. -l /var/log/dnscheck6.log -i {{ tykdnscheck_okservers_v6 | join(' ') }} -g '{{ tykdnscheck_goodmessage }}' -b '{{ tykdnscheck_badmessage }}'"
        user: "0"

