---
- name: "restart django runworker instances"
  shell: "for worker in $(/usr/local/bin/supervisorctl status runworker: | cut -d ' ' -f 1); do /usr/local/bin/supervisorctl restart $worker; done"

- name: "restart django manage.py worker instances"
  command: "/usr/local/bin/supervisorctl restart {{ item }}"
  with_dict: "{{ django_manage_workers | default({}) }}"

- name: "reread and update supervisord"
  command: "/usr/local/bin/supervisorctl reread && /usr/local/bin/supervisorctl update"

