---
- name: "Install pip"
  pkgng:
    name: "py27-pip"
    state: "present"

- name: "Install virtualenv"
  pkgng:
    name: "py27-virtualenv"
    state: "present"

- name: "Install python35"
  pkgng:
    name: "python35"
    state: "present"

- name: "Create virtualenv"
  pip:
    virtualenv_python: "python3"
    virtualenv: "{{ virtualenv_path }}"

- name: "Install radicale in virtualenv"
  pip:
    virtualenv: "{{ virtualenv_path }}"
    name: "radicale"

- name: "Copy radicale config"
  template:
    src: "radicale-config.j2"
    dest: "/usr/local/etc/radicale/config"
    owner: "root"
    group: "wheel"
    mode: "0644"

- name: "Copy radicale logging config"
  template:
    src: "radicale-logging.j2"
    dest: "/usr/local/etc/radicale/logging"
    owner: "root"
    group: "wheel"
    mode: "0644"

- name: "Copy radicale rights config"
  template:
    src: "radicale-rights.j2"
    dest: "/usr/local/etc/radicale/rights"
    owner: "root"
    group: "wheel"
    mode: "0644"

- name: "Fix permissions of radicale storage location"
  file:
    dest: "{{ radicale_datadir }}"
    owner: "radicale"
    group: "radicale"
    mode: "0700"
    state: "directory"

