---
- name: "Add radicale user"
  user:
    name: "radicale"
    comment: "Radicale daemon"
    home: "/nonexistant"
    shell: "/usr/sbin/nologin"
    uid: "974"

- name: "Install pip"
  pkgng:
    name: "py27-pip"
    state: "present"

- name: "Install virtualenv"
  pkgng:
    name: "py27-virtualenv"
    state: "present"

- name: "Install python35"
  pkgng:
    name: "python35"
    state: "present"

- name: "Create virtualenv and install radicale in it"
  pip:
    virtualenv_python: "/usr/local/bin/python3.5"
    virtualenv: "{{ virtualenv_path }}"
    name: "radicale"

- name: "Create radicale config directory"
  file:
    path: "{{ radicale_configdir }}"
    state: "directory"

- name: "Copy radicale config"
  template:
    src: "radicale-config.j2"
    dest: "{{ radicale_configdir }}/config"
    owner: "root"
    group: "wheel"
    mode: "0644"

- name: "Copy radicale logging config"
  template:
    src: "radicale-logging.j2"
    dest: "{{ radicale_configdir }}/logging"
    owner: "root"
    group: "wheel"
    mode: "0644"

- name: "Copy radicale rights config"
  template:
    src: "radicale-rights.j2"
    dest: "{{ radicale_configdir }}/rights"
    owner: "root"
    group: "wheel"
    mode: "0644"

- name: "Fix permissions of radicale storage location"
  file:
    dest: "{{ radicale_datadir }}"
    owner: "radicale"
    group: "radicale"
    mode: "0700"
    state: "directory"

