---
- name: "Create supervisord.d config file to run radicale"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "radicale"
    supervisord_programs:
      - name: "radicale"
        comment: "run radicale"
        command: "{{ virtualenv_path }}/bin/python {{ virtualenv_path }}/bin/radicale -C /usr/local/etc/radicale/config"
        user: "radicale"
        priority: "1"

