---
- name: "Copy metabase config file"
  template:
    src: "metabase.conf.j2"
    dest: "/usr/local/etc/metabase.conf"
    owner: "{{ metabase_user }}"
    group: "{{ metabase_group }}"
    mode: "600"

- name: "Enable metabase in rc.conf"
  service:
    name: "metabase"
    enabled: yes

