---
- name: "Create supervisord.d config file to run nipapwww"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "nipapwww"
    supervisord_programs:
      - name: "nipapwww"
        comment: "run nipapwww"
        command: "/usr/local/bin/paster serve /usr/local/etc/nipap/nipap-www.ini"
        user: "nipap"

