---
- name: "Install elasticsearch"
  pkgng:
    name: "elasticsearch5"
    state: "present"

- name: "Enable elasticsearch"
  service:
    name: "elasticsearch"
    enabled: yes
  notify: "restart elasticsearch"

