---
- name: "Install logstash5"
  pkgng:
    name: "logstash5"
    state: "present"

- name: "Enable logstash"
  service:
    name: "logstash"
    enabled: yes
  notify: "start logstash"

- name: "Configure logstash"
  template:
    src: "logstash.conf.j2"
    dest: "/usr/local/etc/logstash/logstash.conf"
    owner: "root"
    group: "wheel"
    mode: "0644"
  notify: "restart logstash"

