---
- name: "kldload pflog module"
  command: "/sbin/kldload pflog"

- name: "kldload pf module"
  command: "/sbin/kldload pf"

- name: "reload pf"
  service:
    name: "pf"
    state: "reloaded"

- name: "kldload carp module"
  command: "/sbin/kldload carp"


