---
- name: "start supervisord"
  service:
    name: "supervisord"
    state: "started"

- name: "reread supervisord config"
  command: "/usr/local/bin/supervisorctl reread"

- name: "update supervisord config"
  command: "/usr/local/bin/supervisorctl update"

