---
- name: Install ezjail
  become: yes
  pkgng:
    name=ezjail
    state=present

- name: Enable ezjail
  become: yes
  service:
    name=ezjail
    enabled=yes

- name: Copy ezjail config
  become: yes
  template:
    src=ezjail.conf.j2
    dest=/usr/local/etc/ezjail.conf

- name: Delete the ezjail flavour
  become: yes
  file:
    path=/usr/jails/flavours/tykbasic/
    state=absent

- name: Copy ezjail flavour
  become: yes
  copy:
    owner=root
    group=wheel
    mode=644
    src=ezjailflavours/tykbasic
    dest=/usr/jails/flavours

- name: Make the ezjail flavour script executable
  become: yes
  file:
    path=/usr/jails/flavours/tykbasic/etc/rc.d/ezjail.flavour.tykbasic
    owner=root
    group=wheel
    mode=0744

