---
- name: Install ezjail
  pkgng:
    name=ezjail
    state=present

- name: Enable ezjail
  service:
    name=ezjail
    enabled=yes

- name: Copy ezjail config
  template:
    src=ezjail.conf.j2
    dest=/usr/local/etc/ezjail.conf

