---
- name: Delete the ezjail flavour
  file:
    path=/usr/jails/flavours/tykbasic/
    state=absent

- name: Create ezjail flavour directory
  file:
    path=/usr/jails/flavours/{{ ezjail_flavourname }}/
    state=directory

- name: Copy ezjail flavour
  copy:
    owner=root
    group=wheel
    mode=644
    src=ezjailflavour/
    dest=/usr/jails/flavours/{{ ezjail_flavourname }}/

- name: Add the ssh key for the ansible user
  copy:
    owner=1337
    group=1337
    mode=644
    content="{{ ansible_authorized_keys_file }}"
    dest="/usr/jails/flavours/{{ ezjail_flavourname }}/usr/home/ansible/.ssh/authorized_keys"

- name: Copy the ezjail flavour script template
  template:
    src=ezjail.flavour.j2
    dest=/usr/jails/flavours/{{ ezjail_flavourname }}/etc/rc.d/ezjail.flavour.{{ ezjail_flavourname }}
    owner=root
    group=wheel
    mode=0744

