---
- name: get svn version of /usr/usr
  shell: /usr/bin/svnlite info /usr/src/ | grep "^Revision: " | cut -d " " -f 2
  args:
    executable=/bin/sh
  register: usr_src_rev

- name: Get sources from svn when needed
  shell: "/usr/bin/svnlite update -r{{ freebsd_svn_revision }} https://svn0.eu.freebsd.org/base/stable/{{ ansible_distribution_release.split('.')[0] }}/ /usr/src/"
  args:
    executable=/bin/sh
  when: usr_src_rev.stdout < freebsd_svn_revision

- name: Get the svn revision of the world (well, kernel really) in /usr/obj
  shell: /usr/bin/strings /usr/obj/usr/src/sys/*/kernel | grep -E --only "^FreeBSD .* #[0-9]+ r([0-9]{6})" | grep -E --only [0-9]{6}
  args:
    executable=/bin/sh
  register: usr_obj_rev

- name: build world and kernel when needed
  shell: make -j {{ ansible_processor_count }} buildworld && make -j {{ ansible_processor_count }} buildkernel
  args: 
    executable=/bin/sh
    chdir=/usr/src 
  when: usr_obj_rev.stdout < freebsd_svn_revision

- name: Get the svn revision of the new world (well, kernel really) in /usr/obj
  shell: /usr/bin/strings /usr/obj/usr/src/sys/*/kernel | grep -E --only "^FreeBSD .* #[0-9]+ r([0-9]{6})" | grep -E --only [0-9]{6}
  args: 
    executable=/bin/sh
  register: usr_obj_rev
  when: usr_obj_rev.stdout < minimum_svn_rev

- name: Get kernel svn revision from uname 
  shell: /usr/bin/uname -v | /usr/bin/grep -E --only "[0-9]{6}"
  args: 
    executable=/bin/sh
    chdir=/usr/src 
  register: uname_rev

- name: Check if we need to install a new world and kernel
  fail: msg="Please run installkernel, reboot, mergemaster -pFUi, installworld, mergemaster -FUi, ezjail-admin update -i, jailmergemaster.sh"
  when: uname_rev.stdout < usr_obj_rev.stdout

