---
- name: "Create supervisord.d config file to run iperf3"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "iperf3"
    supervisord_programs:
      - comment: "run iperf3 server"
        name: "iperf3"
        command: "/usr/local/bin/iperf3 -s"
        user: "nobody"

