---
- name: "Get certgrinder code from git"
  git:
    repo: "https://github.com/tykling/certgrinder"
    dest: "/usr/home/{{ certgrinder_user }}/certgrinder"
    force: yes
    version: "master"

- name: "Fix permissions of certgrinder dir"
  file:
    path: "/usr/home/{{ certgrinder_user }}/certgrinder"
    owner: "{{ certgrinder_user }}"
    group: "{{ certgrinder_user }}"
    recurse: yes

