---
- name: "Create certificates directory"
  file:
    dest: "/usr/home/{{ certgrinder_user }}/certificates"
    state: "directory"
    mode: "0750"
    owner: "{{ certgrinder_user }}"

- name: "Create certgrinder.yml config file"
  template:
    src: "certgrinder.yml.j2"
    dest: "/usr/home/{{ certgrinder_user }}/certgrinder.yml"
    owner: "{{ certgrinder_user }}"
    mode: "0644"

