---
- name: "Install python"
  pkgng:
    name: "python"
    state: "present"

- name: "Install pip"
  pkgng:
    name: "py27-pip"
    state: "present"

- name: "Install virtualenv"
  pkgng:
    name: "py27-virtualenv"
    state: "present"

- name: "Create new virtualenv and install cryptography. Force pip to use /usr/local/ OpenSSL libs+include because https://github.com/pyca/cryptography/issues/3693#issuecomment-449982895"
  pip:
    virtualenv_python: "python"
    name: "cryptograpy"
    virtualenv: "/usr/home/{{ certgrinder_user }}/virtualenv"
    extra_args: '--global-option=build_ext --global-option="-I/usr/local/include" --global-option="-L/usr/local/lib"'

- name: "Install the rest of requirements.txt modules with pip"
  pip:
    virtualenv_python: "python"
    requirements: "/usr/home/{{ certgrinder_user }}/certgrinder/requirements.txt"
    virtualenv: "/usr/home/{{ certgrinder_user }}/virtualenv"

