---
- name: "add syslog.d config for certgrinder"
  copy:
    src: "certgrinder-syslogd.conf"
    dest: "/usr/local/etc/syslog.d/certgrinder.conf"
  notify: "restart syslogd"

- name: "Make sure /var/log/certgrinder.log exists"
  copy:
    dest: "/var/log/certgrinder.log"
    content: ""
    force: False
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"

