---
- name: "Add certgrinder user"
  user:
    name: "{{ certgrinder_user }}"
    comment: "certgrinder user"
    ssh_key_type: "ed25519"
    generate_ssh_key: True
  notify:
    - "certgrinder ssh key created email"

- name: "Add sudoers permission so the certgrinder user can run post renew hooks"
  lineinfile:
    dest: "/usr/local/etc/sudoers"
    state: "present"
    line: "{{ certgrinder_user }} ALL=(ALL) NOPASSWD: {{ item }}"
    validate: "visudo -cf %s"
  with_items: "{{ certgrinder_post_renew_hooks }}"

