---
- name: Create webusers homedir
  file:
    path: /usr/webhomes
    state: directory
    mode: "755"

- name: Create webusers group
  group:
    name: webusers
    state: present

- name: Create chroots
  file:
    path: "/usr/webhomes/{{ item.key }}chroot"
    state: directory
    mode: "755"
  with_dict: "{{ webusers | default({}) }}"
  tags:
    - usermanagement

- name: Create web users
  user:
    name: "{{ item.key }}"
    comment: "{{ item.value.name }}"
    group: webusers
    home: "/usr/webhomes/{{ item.key }}chroot/{{ item.key }}"
    shell: "/bin/sh"
  with_dict: "{{ webusers | default({}) }}"
  tags:
    - usermanagement

- name: Create wwwroots
  file:
    path: "/usr/webhomes/{{ item.key }}chroot/{{ item.key }}/wwwroot"
    state: directory
    mode: "755"
    owner: "{{ item.key }}"
    group: webusers
  with_dict: "{{ webusers | default({}) }}"
  tags:
    - usermanagement

- name: Add SSH keys
  authorized_key:
    user: "{{ item.key }}"
    key: "{{ item.value.pubkey }}"
    state: present
    exclusive: yes
  with_dict: "{{ webusers | default({}) }}"
  tags:
    - usermanagement

