---
- include_tasks: "ansible.yml"
- include_tasks: "user.yml"
- include_tasks: "syslog.yml"
- include_tasks: "newsyslog.yml"
- include_tasks: "sshfp.yml"
- include_tasks: "cronjob.yml"
  when: ansible_server_checkstuff_cronjob

