---
- name: "Get sshfp code from git"
  git:
    repo: "https://github.com/tykling/check_sshfp"
    dest: "/usr/home/{{ ansible_user }}/check_sshfp"
    force: yes
    version: "master"
    accept_hostkey: yes

- name: "Install py27-dnspython"
  pkgng:
    name: "py27-dnspython"
    state: "present"

- name: "Enable nightly cronjob to check various things"
  cron:
    name: "ansible check_stuff.sh"
    hour: "4"
    minute: "30"
    job: "/usr/local/etc/ansible/roles/library/check_stuff.sh {{ ansible_admin_email }}"
    cron_file: "/etc/crontab"
    user: "ansible"

