---
- name: "add syslog.d config for ansible"
  copy:
    src: "ansible-syslogd.conf"
    dest: "/usr/local/etc/syslog.d/ansible.conf"
  notify: "restart syslogd"

- name: "Make sure /var/log/ansible.log exists"
  copy:
    dest: "/var/log/ansible.log"
    content: ""
    force: no
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"

