---
- name: "Add ansible user"
  user:
    name: "{{ ansible_user }}"
    comment: "ansible user"
    ssh_key_type: "ed25519"
    generate_ssh_key: True

- name: "Install .bashrc for ansible user"
  template:
    src: ".bashrc.j2"
    dest: "/usr/home/{{ ansible_user }}/.bashrc"
    owner: "ansible"
    group: "ansible"
    mode: "0644"

