---
- name: "Add ansible user"
  user:
    name: "{{ ansible_user }}"
    comment: "ansible user"
    ssh_key_type: "ed25519"
    generate_ssh_key: True

- name: "Install .bashrc for ansible user"
  template:
    src: ".bashrc.j2"
    dest: "/usr/home/{{ ansible_user }}/.bashrc"
    owner: "ansible"
    group: "ansible"
    mode: "0644"

- name: "Make sure we have an ssh key for root to deploy config"
  user:
    name: "root"
    ssh_key_type: "ed25519"
    generate_ssh_key: True

- name: "Add ssh config for github.com"
  blockinfile:
    create: yes
    dest: "/root/.ssh/config"
    marker: "# {mark} ANSIBLE MANAGED BLOCK github.com ssh config"
    content: |
      Host            github.com
      Hostname        github.com
      IdentitiesOnly  yes
      User            git
    mode: "0600"

