---
- name: "copy supervisord syslog.d config"
  copy:
    src: "supervisord-syslogd.conf"
    dest: "/usr/local/etc/syslog.d/supervisord.conf"
    mode: "0644"
    owner: "root"
    group: "wheel"
  notify:
    - "restart syslogd"

- name: "copy supervisord newsyslog.d config"
  copy:
    src: "supervisord-syslogd.conf"
    dest: "/usr/local/etc/newsyslog.conf.d/supervisord.conf"
    mode: "0644"
    owner: "root"
    group: "wheel"

- name: "Make sure supervisord logfile exists"
  copy:
    dest: "/var/log/supervisord.log"
    content: ""
    force: "no"
  notify:
    - "restart syslogd"

