---
- name: Install php
  pkgng:
    name: php56
    state: present

- name: Install php-pgsql
  pkgng:
    name: php56-pgsql
    state: present

- name: Enable php-fpm
  service:
    name: php-fpm
    enabled: yes

- name: Configure php-fpm
  template:
    src: php-fpm.conf.j2
    dest: /usr/local/etc/php-fpm.conf

- name: Create php socket directory
  file:
    path: /var/php
    state: directory
    owner: www
    group: www

- name: Start php-fpm (if not running)
  service:
    name: php-fpm
    state: started

- name: Reload php-fpm config
  service:
    name: php-fpm
    state: reloaded

