---
- include_tasks: "postgresql.yml"
- include_tasks: "ip4r.yml"
- include_tasks: "syslog.yml"
- include_tasks: "newsyslog.yml"
- include_tasks: "supervisord.yml"
- include_tasks: "periodic-daily.yml"
- include_tasks: "pgbouncer.yml"
- include_tasks: "replicabackup.yml"

