---
- name: "Install PostgreSQL"
  pkgng:
    name: "postgresql96-server"
    state: "present"

- name: "Enable PostgreSQL"
  service:
    name: "postgresql"
    enabled: yes

- name: "Initialise PostgreSQL database"
  command: "/usr/sbin/service postgresql initdb"
  args:
    creates: "{{ postgresql_homedir }}/data"

- name: "Start PostgreSQL"
  service:
    name: "postgresql"
    state: "started"

