---
- name: "Install PostgreSQL"
  pkgng:
    name: "postgresql96-server"
    state: "present"

- name: "Enable PostgreSQL"
  service:
    name: "postgresql"
    enabled: yes

- name: "Make sure postgres homedir is owned by postgres:postgres"
  file:
    dest: "{{ postgresql_homedir }}"
    owner: "postgres"
    group: "postgres"
    state: "directory"
  notify: "reload postgresql"

- name: "Initialise PostgreSQL database"
  command: "/usr/sbin/service postgresql initdb"
  args:
    creates: "{{ postgresql_datadir }}"
  notify: "reload postgresql"

- name: "Copy config file"
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_datadir }}/postgresql.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0600"
  notify: "restart postgresql"

