---
- name: "Install PostgreSQL"
  pkgng:
    name: "postgresql96-server"
    state: "present"

- name: "Enable PostgreSQL"
  service:
    name: "postgresql"
    enabled: yes

- name: "Make sure postgres homedir is owned by postgres:postgres"
  file:
    dest: "{{ postgresql_homedir }}"
    owner: "postgres"
    group: "postgres"
    state: "directory"

- name: "Initialise PostgreSQL database"
  command: "/usr/sbin/service postgresql initdb"
  args:
    creates: "{{ postgresql_homedir }}/data96"

- name: "Start PostgreSQL"
  service:
    name: "postgresql"
    state: "started"

