---
- name: "Install PostgreSQL"
  pkgng:
    name: "postgresql{{ postgresql_version }}-server"
    state: "present"

- name: "Install PostgreSQL controb"
  pkgng:
    name: "postgresql{{ postgresql_version }}-contrib"
    state: "present"

- name: "Make sure postgres homedir is owned by postgres:postgres"
  file:
    dest: "{{ postgresql_homedir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    state: "directory"
  notify: "reload postgresql"

- name: "Initialise PostgreSQL database"
  command: "/usr/sbin/service postgresql oneinitdb"
  args:
    creates: "{{ postgresql_datadir }}"
  notify: "reload postgresql"

- name: "Copy config file"
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_datadir }}/postgresql.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: "0600"
  notify: "restart postgresql"

- name: "Enable daily postgres vacuum in /etc/periodic.conf"
  sysrc:
    name: "daily_pgsql_vacuum_enable"
    value: "YES"
    dest: "/etc/periodic.conf"
  when: daily_pgsql_vacuum_enable

- name: "Enable daily postgres backup in /etc/periodic.conf"
  sysrc:
    name: "daily_pgsql_backup_enable"
    value: "YES"
    dest: "/etc/periodic.conf"

- name: "Set destination dir for postgres backups in /etc/periodic.conf"
  sysrc:
    name: "daily_pgsql_backupdir"
    value: "{{ postgresql_backup_path }}"
    dest: "/etc/periodic.conf"

- name: "Set savedays for postgres backups in /etc/periodic.conf"
  sysrc:
    name: "daily_pgsql_savedays"
    value: "{{ postgresql_backup_savedays }}"
    dest: "/etc/periodic.conf"

- name: "Set daily_pgsql_user /etc/periodic.conf"
  sysrc:
    name: "daily_pgsql_user"
    value: "{{ postgresql_user }}"
    dest: "/etc/periodic.conf"

