---
- name: "Create supervisord.d config file to run postgres"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "postgresql"
    supervisord_programs:
      - name: "postgresql"
        comment: "run postgresql"
        command: "/usr/local/bin/postgres -D {{ postgresql_datadir }}"
        user: "{{ postgresql_user }}"
        startretries: 200

