---
- name: "Install snmp_exporter"
  pkgng:
    name: "snmp_exporter"
    state: "present"

- name: "Install snmp_exporter_generator configuration"
  template:
    src: "generator.yml.j2"
    dest: "/usr/local/etc/snmp_exporter/generator.yml"
    owner: "root"
    group: "wheel"
    mode: "0755"
  register: "generatorresult"

- name: "Run snmp_exporter_generator because generator.yml was changed"
  command: "/usr/local/bin/snmp_exporter_generator generate"
  when: generatorresult is changed
  notify:
    - "restart snmp_exporter"

- name: "Create supervisord.d config file to run snmp_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "snmp_exporter"
    supervisord_programs:
      - name: "snmp_exporter"
        comment: "run snmp_exporter"
        command: "/usr/local/bin/snmp_exporter --config.file=/usr/local/etc/snmp_exporter/snmp.yml --web.listen-address={{ snmp_exporter_listen_address }} --log.level={{ snmp_exporter_log_level }}"
        user: "nobody"

- name: "Create extra snmp MIB files..."
  copy:
    owner: "root"
    group: "wheel"
    mode: "0644"
    content: "{{ item.content }}"
    dest: "/usr/local/share/snmp/mibs/{{ item.filename }}"
  with_items: "{{ snmp_exporter_extra_mibs | default([]) }}"

- name: "Make sure /usr/local/etc/snmp/ folder exists"
  file:
    path: "/usr/local/etc/snmp"
    state: "directory"

- name: "Add extra snmp MIB files to /usr/local/etc/snmp/snmp.conf"
  lineinfile:
    dest: "/usr/local/etc/snmp/snmp.conf"
    regexp: "^mibs +{{ item.mibname }}$"
    line: "mibs +{{ item.mibname }}"
  with_items: "{{ snmp_exporter_extra_mibs | default([]) }}"

