---
- name: "Install syslog-ng"
  pkgng:
    name: "syslog-ng"
    state: "present"

- name: "Copy syslog-ng.conf"
  template:
    src: "syslog-ng.conf.j2"
    dest: "/usr/local/etc/syslog-ng.conf"
  notify: "reload syslog-ng"

