---
- name: "add syslog.d config for grafana"
  copy:
    src: "grafana-syslogd.conf"
    dest: "/usr/local/etc/syslog.d/grafana.conf"
  notify: "restart syslogd"

- name: "Make sure /var/log/grafana.log exists"
  copy:
    dest: "/var/log/grafana.log"
    content: ""
    force: False
    owner: "root"
    group: "wheel"
    mode: "644"
  notify: "restart syslogd"

