---
- name: "Get code from git"
  git:
    repo: "{{ tykbackup_github_repo_url }}"
    dest: "{{ tykbackup_checkout_path }}"
    force: yes
    version: "{{ tykbackup_github_branch }}"

- name: "Copy zfscmd.sh into place"
  copy:
    src: "{{ tykbackup_checkout_path }}/zfscmd.sh"
    dest: "/usr/local/bin/zfscmd.sh"
    owner: "root"
    group: "wheel"
    mode: "0755"
    remote_src: yes

