---
- name: "Install charybdis"
  pkgng:
    name: "charybdis"
    state: "present"

- name: "Enable charybdis"
  service:
    name: "charybdis"
    enabled: yes

- name: "Run certgrinder"
  include_role:
    name: "certgrinder_run"
    tasks_from: "run_certgrinder"

