---
- name: "Install opendkim"
  pkgng:
    name: "opendkim"
    state: "present"

- name: "Create opendkim socket directory"
  file:
    path: "/var/spool/postfix/opendkim"
    state: "directory"
    owner: "postfix"
    group: "wheel"
    mode: "755"

- name: "Copy opendkim.conf"
  template:
    src: "opendkim.conf.j2"
    dest: "/usr/local/etc/opendkim.conf"

- name: "Install opendkim.keytable"
  template:
    src: "opendkim.keytable.j2"
    dest: "/usr/local/etc/opendkim.keytable"
    owner: "root"
    group: "wheel"
    mode: "644"

- name: "Install opendkim.signingtable"
  template:
    src: "opendkim.signingtable.j2"
    dest: "/usr/local/etc/opendkim.signingtable"
    owner: "root"
    group: "wheel"
    mode: "644"

- name: "Create opendkim key directory"
  file:
    path: "/usr/local/etc/opendkim"
    state: "directory"
    owner: "postfix"
    group: "postfix"
    mode: "500"

- name: "Create opendkim keys"
  copy:
    owner: "postfix"
    group: "postfix"
    mode: "600"
    content: "{{ item.value }}"
    dest: "/usr/local/etc/opendkim/{{ item.key }}-default.private"
  with_dict: "{{ dkimkeys | default({}) }}"

- name: "Enable milteropendkim in rc.conf"
  sysrc:
    name: "milteropendkim_enable"
    value: "yes"

- name: "Set milteropendkim_cfgfile in rc.conf"
  sysrc:
    name: "milteropendkim_cfgfile"
    value: "/usr/local/etc/opendkim.conf"

- name: "Set milteropendkim_uid in rc.conf"
  sysrc:
    name: "milteropendkim_uid"
    value: "postfix"

- name: "Set milteropendkim_socket in rc.conf (workaround ports PR 222122)"
  sysrc:
    name: "milteropendkim_socket"
    value: "local:/var/spool/postfix/opendkim/opendkim.sock"

- name: "Restart milteropendkim"
  service:
    name: "milter-opendkim"
    state: "restarted"

