---
- name: Install postfix
  pkgng:
    name: postfix
    state: present

- name: Enable postfix
  service:
    name: postfix
    enabled: yes

- name: Copy postfix main.cf
  template:
    src: main.cf.j2
    dest: /usr/local/etc/postfix/main.cf

- name: Copy postfix smtpd_sender_login_maps.sql
  template:
    src: smtpd_sender_login_maps.sql
    dest: /usr/local/etc/postfix/smtpd_sender_login_maps.sql
    mode: "600"

- name: Copy postfix virtual_alias_maps.sql
  template:
    src: virtual_alias_maps.sql
    dest: /usr/local/etc/postfix/virtual_alias_maps.sql
    mode: "600"

- name: Copy postfix virtual_mailbox_maps.sql
  template:
    src: smtpd_sender_login_maps.sql
    dest: /usr/local/etc/postfix/virtual_mailbox_maps.sql
    mode: "600"

- name: Run postalias
  shell: /usr/local/sbin/postalias /etc/aliases

- name: Copy postfix transport file
  template:
    mode: "644"
    src: transport.j2
    dest: /usr/local/etc/postfix/transport

- name: Enable submission in master.cf
  blockinfile:
    create: yes
    dest: /usr/local/etc/postfix/master.cf
    marker: "# {mark} ANSIBLE MANAGED BLOCK submission"
    content: |
      submission inet n       -       n       -       -       smtpd
        -o syslog_name=postfix/submission
        -o smtpd_tls_security_level=encrypt
        -o smtpd_sasl_auth_enable=yes
        -o smtpd_reject_unlisted_recipient=no
        -o smtpd_client_restrictions=
        -o smtpd_helo_restrictions=
        -o smtpd_sender_restrictions=
        -o smtpd_recipient_restrictions=
        -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
        -o milter_macro_daemon_name=ORIGINATING

- name: Restart Postfix
  service:
    name: postfix
    state: restarted

- name: Add keep a years maillogs in newsyslog.conf
  lineinfile:
    dest: /etc/newsyslog.conf
    regexp: "^/var/log/maillog "
    line: "/var/log/maillog                        640  365   *    @T00  JC"

