---
- name: "Install openbgpd"
  pkgng:
    name: "openbgpd"
    state: "present"

- name: "Copy openbgpd config"
  template:
    src: "openbgpd.conf.j2"
    dest: "/usr/local/etc/bgpd.conf"
    mode: "0600"

