---
- include_vars: "/usr/local/etc/ansible/host_vars/{{ ansible_nodename }}-secrets.yml"
  tags:
    - always

- name: Copy environment_settings.py into place
  become: yes
  template:
    src=roles/django_server/templates/environment_settings.py.j2
    dest="{{ django_env_settings_path }}"
  tags:
    - codedeploy

- name: Run collectstatic
  become: yes
  django_manage:
    command=collectstatic
    app_path="{{ django_root }}"
  tags:
    - codedeploy

- name: Run compilemessages
  become: yes
  django_manage:
    command=compilemessages
    app_path="{{ django_root }}"
  tags:
    - codedeploy
