---
- name: Install git
  pkgng:
    name: git
    state: present

- name: Remove old code
  file:
    path: "{{ django_root }}"
    state: absent
  tags:
    - codedeploy
  
- name: Get code from git
  git:
    repo: "{{ github_repo_url }}"
    dest: /tmp/git
    force: yes
    version: "{{ github_branch }}"
  tags:
    - codedeploy

- name: Move code to django root
  command: "mv /tmp/git/blog_censurfridns_dk {{ django_root }}"
  tags:
    - codedeploy

- name: Make manage.py executable
  file:
    path: "{{ django_root }}manage.py"
    mode: "755"
  tags:
    - codedeploy

