---
- name: Install git
  become: yes
  pkgng:
    name=git
    state=present

- name: Remove old code
  become: yes
  file:
    path={{ django_root }}
    state=absent
  tags:
    - codedeploy
  
- name: Get code from git
  become: yes
  git:
    repo={{ github_repo_url }}
    dest=/tmp/git
    force=yes
    version={{ github_branch }}
  tags:
    - codedeploy

- name: Move code to django root
  become: yes
  command: "mv /tmp/git/blog_censurfridns_dk {{ django_root }}"
  tags:
    - codedeploy

- name: Make manage.py executable
  become: yes
  file:
    path="{{ django_root }}manage.py"
    mode=0755
  tags:
    - codedeploy
