---
- name: Install uwsgi
  pkgng:
    name=uwsgi
    state=present

- name: Enable uwsgi
  service:
    name=uwsgi
    enabled=yes

- name: Define uwsgi profiles in rc.conf
  sysrc:
    name: uwsgi_profiles
    value: "django"

- name: Define uwsgi flags in rc.conf
  sysrc:
    name: uwsgi_django_flags
    value: "--ini /usr/local/etc/uwsgi/uwsgi.ini --logger syslog --stats /tmp/uwsgi-stats.sock"

- name: Create uwsgi config directory
  file:
    path=/usr/local/etc/uwsgi
    state=directory

- name: Copy uwsgi config file
  template:
    src=uwsgi.ini.j2
    dest=/usr/local/etc/uwsgi/uwsgi.ini

- name: Start uwsgi (if neccesary)
  service:
    name=uwsgi
    state=started

- name: Reload uwsgi
  service:
    name=uwsgi
    state=reloaded
  tags:
    - codedeploy

