---
- name: "Get code from git"
  git:
    repo: "{{ tykbackup_github_repo_url }}"
    dest: "{{ tykbackup_checkout_path }}"
    force: yes
    version: "{{ tykbackup_github_branch }}"

- name: "Copy 999.tykbackup periodic script into place"
  copy:
    src: "{{ tykbackup_checkout_path }}/999.tykbackup"
    dest: "/usr/local/etc/periodic/daily/999.tykbackup"
    owner: "root"
    group: "wheel"
    mode: "0755"
    remote_src: yes

