---
- name: "Install mbuffer"
  pkgng:
    name: "mbuffer"
    state: "present"

- name: "configure tykbackup"
  blockinfile:
    dest: "/etc/periodic.conf"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK tykbackup"
    block: |
      #daily tykbackup
      daily_tykbackup_enable="YES"
      daily_tykbackup_targethost="{{ tykbackup_target_host }}"
      daily_tykbackup_targetuser="{{ tykbackup_target_user }}"
      daily_tykbackup_targetfs="{{ tykbackup_target_zfs }}"
      daily_tykbackup_pools="{{ tykbackup_pools | join(' ') }}"
      daily_tykbackup_skip="{{ tykbackup_skip_datasets | default([]) | join(' ') }}"

- name: "make sure we have an ssh key for root"
  user:
    name: "root"
    ssh_key_type: "ed25519"
    generate_ssh_key: True

