---
- name: "kldload pflog module"
  command: "/sbin/kldload pflog"
  args:
    creates: "/dev/pf"

- name: "kldload pf module"
  command: "/sbin/kldload pf"
  args:
    creates: "/dev/pf"

- name: "reload pf"
  service:
    name: "pf"
    state: "reloaded"
  async: 0
  poll: 0
  ignore_errors: true

