---
- name: Install nginx
  become: yes
  pkgng:
    name=nginx
    state=present

- name: Enable nginx
  become: yes
  service:
    name=nginx
    enabled=yes

- name: Copy nginx config
  become: yes
  template:
    src=nginx.conf.j2
    dest=/usr/local/etc/nginx/nginx.conf

- name: Copy nginx TLS config
  become: yes
  template:
    src=tls.conf.j2
    dest=/usr/local/etc/nginx/tls.conf

- name: Copy nginx securityheaders.conf
  become: yes
  template:
    src=securityheaders.conf.j2
    dest=/usr/local/etc/nginx/securityheaders.conf

- name: Copy nginx proxyheaders.conf
  become: yes
  template:
    src=proxyheaders.conf.j2
    dest=/usr/local/etc/nginx/proxyheaders.conf

- name: Create nginx logfile directory
  become: yes
  file:
    path=/usr/local/www/logs
    state=directory

- name: Create nginx vhosts directory
  become: yes
  file:
    path=/usr/local/etc/nginx/vhosts
    state=directory

- name: Create nginx certificates directory
  become: yes
  file:
    path=/usr/local/etc/nginx/certificates
    state=directory

- name: Create dhparam
  become: yes
  shell: "/usr/local/bin/openssl dhparam 4096 > {{ nginx_dhparam_path }}"
  args:
    creates: "{{ nginx_dhparam_path }}"

- include_vars: "/usr/local/etc/ansible/host_vars/nginx-acl.yml"
  ignore_errors: yes
  tags:
    - always

- name: Create nginx acl.conf
  become: yes
  copy:
    owner=root
    group=wheel
    mode=600
    content="{{ nginx_acl }}"
    dest="/usr/local/etc/nginx/acl.conf"
  when: nginx_acl is defined

- include: vhosts.yml

- name: Start Nginx (if not running)
  become: yes
  service:
    name=nginx
    state=started

- name: Reload nginx config
  become: yes
  service:
    name=nginx
    state=reloaded

- name: Copy nginx OCSP priming script
  become: yes
  copy:
    owner=root
    group=wheel
    mode=755
    src=prime_nginx_ocsp.sh
    dest=/usr/local/bin/prime_nginx_ocsp.sh

- name: Run nginx ocsp priming script
  become: yes
  command: /usr/local/bin/prime_nginx_ocsp.sh

- name: Make sure hourly cronjob for nginx ocsp priming is in place
  become: yes
  cron:
    name="nginx ocsp priming script (every hour)"
    minute="{{ 59 |random }}"
    job="/usr/local/bin/prime_nginx_ocsp.sh"
    cron_file="/etc/crontab"
    user="nobody"
