---
- name: "Create dhparam directory"
  file:
    path: "{{ dhparam_path | dirname }}"
    state: "directory"

- name: "Create dhparams"
  shell: "/usr/local/bin/openssl dhparam 4096 > {{ dhparam_path }}"
  args:
    creates: "{{ dhparam_path }}"

