---
- name: "Install blackbox_exporter"
  pkgng:
    name: "blackbox_exporter"
    state: "present"

- name: "Enable blackbox_exporter"
  service:
    name: "blackbox_exporter"
    enabled: yes

- name: "Set blackbox_exporter args in /etc/rc.conf"
  sysrc:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items: "{{ blackbox_exporter_args }}"

- name: "Install blackbox_exporter configuration"
  template:
    src: "blackbox_exporter.yml.j2"
    dest: "/usr/local/etc/blackbox_exporter.yml"
    owner: "prometheus"
    group: "prometheus"
    mode: "0755"
  notify:
    - "reload blackbox_exporter"

- name: "Start blackbox_exporter"
  service:
    name: "blackbox_exporter"
    state: "started"
