---
- name: "Include host_vars/{{ ansible_nodename }}-secrets.yml if it exists"
  include_vars: "/usr/local/etc/ansible/host_vars/{{ ansible_nodename }}-secrets.yml"
  ignore_errors: yes
  tags:
    - always

- name: Copy dovecot config
  template:
    src: dovecot.conf.j2
    dest: /usr/local/etc/dovecot/dovecot.conf

- name: Copy dovecot sql config
  template:
    src: dovecot-sql.conf.j2
    dest: /usr/local/etc/dovecot/dovecot-sql.conf
    mode: "600"

- name: Create mailbox folder
  file:
    path: /usr/mailboxes
    state: directory
    mode: "700"
    owner: "{{ dovecot_vmail_username}}"
    group: "{{ dovecot_vmail_groupname}}"

