---
- name: Enable dovecot
  service:
    name: dovecot
    enabled: yes

- name: Start dovecot (if not running)
  service:
    name: dovecot
    state: started

- name: Reload dovecot config
  service:
    name: dovecot
    state: reloaded

