---
- name: Add dovecot.log to syslog.conf
  become: yes
  lineinfile:
    dest=/etc/syslog.conf
    regexp="^local3"
    line="local3.*                                        /var/log/dovecot.log"

- name: Create dovecot.log if it doesn't exist
  become: yes
  file:
    path=/var/log/dovecot.log
    state=touch
    mode=0600

- name: Reload syslogd
  become: yes
  service:
    name=syslogd
    state=reloaded

- name: Add dovecot.log to newsyslog.conf
  become: yes
  lineinfile:
    dest=/etc/newsyslog.conf
    regexp="^/var/log/dovecot.log "
    line="/var/log/dovecot.log                    640  365   *    @T00  JC"

