---
- name: Create virtual mail group
  group:
    name: "{{ dovecot_vmail_groupname }}"
    gid: "{{ dovecot_vmail_gid }}"
    state: present

- name: Create virtual mail user
  user:
    name: "{{ dovecot_vmail_username }}"
    comment: "virtual mail user"
    uid: "{{ dovecot_vmail_uid }}"
    group: "{{ dovecot_vmail_groupname }}"

